server:
  port : 8085
spring:
  application:
    name: course-arrange-service
  datasource:
    url: jdbc:mysql://localhost:3306/cs
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis:
  configuration:
    map-underscore-to-camel-case: true